name: Update MD List

on:
  push:
    paths:
      - '**.md'
    branches:
      - main

jobs:
  update-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Make JSON list
        run: |
          find . -maxdepth 1 -name "*.md" | sed 's|^\./||' | jq -R -s -c 'split("\n")[:-1]' > files.json
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update files.json"
          file_pattern: "files.json"